import pandas as pd
import numpy as np
import re
import pickle
import sklearn
import xgboost
import lightgbm
import warnings

warnings.filterwarnings("ignore")

map = {
    "subtype": ["forward", "local", "ips"],
    "level": ["notice", "warning", "alert"],
    "srccountry": [
        "India",
        "Reserved",
        "United States",
        "Somalia",
        "Netherlands",
        "Australia",
        "Germany",
        "Bulgaria",
        "Cyprus",
        "France",
        "Unknown",
        "Japan",
        "Malaysia",
        "United Arab Emirates",
        "Ireland",
        "Canada",
        "United Kingdom",
        "Hong Kong",
        "Bahrain",
        "Italy",
        "Singapore",
        "Sweden",
        "Brazil",
        "South Africa",
        "Korea, Republic of",
        "Czech Republic",
        "Pakistan",
        "Russian Federation",
        "Thailand",
        "Lithuania",
        "Ecuador",
        "Uzbekistan",
        "Chile",
        "Denmark",
        "Maldives",
        "Portugal",
        "China",
        "Ukraine",
        "New Zealand",
        "Mali",
        "Mongolia",
        "Ghana",
        "Oman",
        "Georgia",
        "Mauritius",
        "Turkey",
        "Taiwan",
        "Spain",
        "Argentina",
        "Saudi Arabia",
        "Finland",
        "Egypt",
        "Romania",
        "Slovenia",
        "Iraq",
        "Belize",
        "Cambodia",
        "Switzerland",
        "Sri Lanka",
        "Philippines",
        "Nigeria",
        "Ethiopia",
        "Serbia",
        "Iran, Islamic Republic of",
        "Armenia",
        "Tunisia",
        "Israel",
        "Belgium",
        "Mexico",
        "Tanzania, United Republic of",
        "Colombia",
        "Isle of Man",
        "El Salvador",
        "Azerbaijan",
        "Indonesia",
        "Greece",
        "Malta",
        "Jordan",
        "Kenya",
        "Belarus",
        "Kazakhstan",
        "Bosnia and Herzegovina",
        "Croatia",
        "Hungary",
        "Qatar",
        "Latvia",
        "Vietnam",
        "Bangladesh",
        "Estonia",
        "Kyrgyzstan",
        "Benin",
        "Albania",
        "Myanmar",
    ],
    "srcintf": ["LLB- Connect", "Local_LAN", "unknown-0", "root"],
    "srcintfrole": ["wan", "undefined"],
    "dstintf": ["Local_LAN", "LLB- Connect"],
    "dstintfrole": ["undefined", "wan"],
    "action": [
        "client-rst",
        "close",
        "accept",
        "server-rst",
        "deny",
        "timeout",
        "ip-conn",
        "dns",
        "dropped",
    ],
    "service": [
        "HTTPS",
        "FTPS",
        "tcp/3349",
        "PING",
        "tcp/44094",
        "ForFTP_DATA",
        "tcp/7143",
        "NHP-FLUX",
        "DNS",
        "icmp/0/8",
        "tcp/51179",
        "tcp/2705",
        "tcp/8501",
        "tcp/8085",
        "tcp/16322",
        "udp/8081",
        "udp/5353",
        "tcp/43894",
        "tcp/58591",
        "tcp/1800",
        "tcp/2023",
        "udp/8083",
        "udp/8080",
        "tcp/9001",
        "HTTP",
        "tcp/43893",
        "tcp/6443",
        "tcp/33335",
        "tcp/8888",
        "tcp/13333",
        "tcp/40501",
        "tcp/1240",
        "tcp/11115",
        "tcp/2005",
        "tcp/2091",
        "tcp/2101",
        "tcp/2090",
        "tcp/33010",
        "udp/1027",
        "RTSP",
        "tcp/32914",
        "udp/8082",
        "tcp/30089",
        "tcp/33389",
        "SMTPS",
        "tcp/26657",
        "tcp/7366",
        "tcp/4433",
        "tcp/33896",
        "tcp/5678",
        "tcp/33000",
        "tcp/26659",
        "tcp/8546",
        "tcp/33892",
        "tcp/41433",
        "tcp/21912",
        "tcp/10433",
        "tcp/5601",
        "tcp/24413",
        "tcp/9650",
        "tcp/18546",
        "tcp/8545",
        "tcp/3789",
        "tcp/1389",
        "VDOLIVE",
        "tcp/9990",
        "tcp/61014",
        "tcp/18545",
        "tcp/16589",
        "tcp/11000",
        "tcp/7433",
        "tcp/22020",
        "tcp/55366",
        "NTP",
        "tcp/26660",
        "tcp/32371",
        "tcp/8815",
        "X-WINDOWS",
        "tcp/43389",
        "tcp/20201",
        "tcp/48942",
        "TELNET",
        "FTP",
        "tcp/8547",
        "udp/22",
        "tcp/50005",
        "tcp/5005",
        "tcp/42914",
        "tcp/49389",
        "tcp/17882",
        "tcp/8845",
        "SNMP",
        "tcp/13384",
        "tcp/1017",
        "tcp/8548",
        "udp/4000",
        "tcp/888",
        "tcp/8819",
        "tcp/8807",
        "tcp/62922",
        "tcp/8820",
        "tcp/14433",
        "tcp/8854",
        "tcp/11114",
        "tcp/15006",
        "tcp/5500",
        "tcp/54077",
        "udp/11211",
        "tcp/2006",
        "tcp/8818",
        "tcp/12433",
        "tcp/34130",
        "tcp/35366",
        "tcp/3200",
        "tcp/14330",
        "tcp/49676",
        "tcp/8934",
        "tcp/6089",
        "tcp/9089",
        "tcp/13389",
        "tcp/39389",
        "tcp/8989",
        "MS-SQL",
        "tcp/11118",
        "tcp/33905",
        "tcp/2999",
        "tcp/44273",
        "tcp/32288",
        "tcp/20412",
        "tcp/41832",
        "tcp/28222",
        "tcp/25898",
        "tcp/9195",
        "tcp
